version: '3.4'

services:
  pokemonreviewapp:
    image: jakkapatchongsuwat/pokemonreviewapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"   # Map port 80 inside the container to port 8080 on the host for HTTP
      - "8443:443"  # Map port 443 inside the container to port 8443 on the host for HTTPS
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    volumes:
      - ./aspnetapp.pfx:/app/aspnetapp.pfx
